name: "wanfall-oops-cross-bmi"
video_datasets:
  - name: "wanfall"
    video_root: "${oc.env:WANFALL_ROOT}/video"
    annotations_file: "hf://simplexsigil2/wanfall/labels/wanfall.csv"
    dataset_fps: 16.0
    split_root: "hf://simplexsigil2/wanfall/splits/cross_bmi"

  - name: "OOPS"
    video_root: "${oc.env:OMNIFALL_ROOT}/OOPS/video"
    annotations_file: "hf://simplexsigil2/omnifall/labels/OOPS.csv"
    dataset_fps: 30.0
    split_root: "hf://simplexsigil2/omnifall/splits"

# Common parameters
target_fps: ${model.model_fps}
vid_frame_count: ${model.num_frames}
num_classes: 16
path_format: "{video_root}/{video_path}{ext}"
