# InternVL models

family: "InternVL"
version: "3_5" # or 3
variant: null
params: "2B"

# Computed paths
name: "${model.family}${model.version}-${model.params}-HF"
checkpoint_path: "OpenGVLab/${model.name}"

needs_video_metadata: false
