# InternVL models
org: OpenGVLab
family: InternVL
version: "3_5"
variant: null
params: 1B # 1B, 2B, 4B, 8B, 14B, 38B

# 30-3, 241-28 MOE models
active_params: null

needs_video_metadata: false

mm_processor_kwargs:
  do_resize: false
