output_format: json
include_role: true
include_definitions: true
include_adherence: true
cot: false
cot_delimiter: "Final Answer:"
few_shot_examples:
  - config/fewshot/walk_example.yaml
  - config/fewshot/fall_example.yaml
model_family: ${model.family}
