name: "video-dataset-cmdfall"
video_datasets:
  - name: "cmdfall"
    video_root: "${oc.env:OMNIFALL_ROOT}/cmdfall/video"
    annotations_file: "hf://simplexsigil2/omnifall/labels/cmdfall.csv"
    dataset_fps: 20.0
    split_root: "hf://simplexsigil2/omnifall/splits"

# Common parameters
target_fps: ${model.model_fps}
vid_frame_count: ${model.num_frames}
num_classes: 16
path_format: "{video_root}/{video_path}{ext}"

# Metric for model selection during training
metric_for_best_model: "eval_balanced_accuracy"
