name: "video-dataset-le2i"
video_datasets:
  - name: "le2i"
    video_root: "${oc.env:OMNIFALL_ROOT}/le2i/video"
    annotations_file: "hf://simplexsigil2/omnifall/labels/le2i.csv"
    dataset_fps: 25.0
    split_root: "hf://simplexsigil2/omnifall/splits"

# Common parameters
target_fps: ${model_fps}
vid_frame_count: ${num_frames}
num_classes: 16
path_format: "{video_root}/{video_path}{ext}"
