name: "feature-dataset-all"
feature_datasets:
  - name: "cmdfall"
    feature_root: "${oc.env:OMNIFALL_ROOT}/cmdfall/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/cmdfall.csv"
    feature_fps: 20.0
    frames_per_feature: 16
    feature_stride: 0.05
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "up_fall"
    feature_root: "${oc.env:OMNIFALL_ROOT}/up_fall/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/up_fall.csv"
    feature_fps: 18.0
    frames_per_feature: 16
    feature_stride: 0.055555556
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "le2i"
    feature_root: "${oc.env:OMNIFALL_ROOT}/le2i/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/le2i.csv"
    feature_fps: 25.0
    frames_per_feature: 16
    feature_stride: 0.04
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "gmdcsa24"
    feature_root: "${oc.env:OMNIFALL_ROOT}/GMDCSA24/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/GMDCSA24.csv"
    feature_fps: 30.0
    frames_per_feature: 16
    feature_stride: 0.033333333
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "edf"
    feature_root: "${oc.env:OMNIFALL_ROOT}/edf/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/edf.csv"
    feature_fps: 30.0
    frames_per_feature: 16
    feature_stride: 0.033333333
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "occu"
    feature_root: "${oc.env:OMNIFALL_ROOT}/occu/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/occu.csv"
    feature_fps: 30.0
    frames_per_feature: 16
    feature_stride: 0.033333333
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "caucafall"
    feature_root: "${oc.env:OMNIFALL_ROOT}/caucafall/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/caucafall.csv"
    feature_fps: 20.0
    frames_per_feature: 16
    feature_stride: 0.05
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "mcfd"
    feature_root: "${oc.env:OMNIFALL_ROOT}/mcfd/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/mcfd.csv"
    feature_fps: 30.0
    frames_per_feature: 16
    feature_stride: 0.033333333
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"

  - name: "OOPS"
    feature_root: "${oc.env:OMNIFALL_ROOT}/OOPS/features/i3d"
    annotations_file: "hf://simplexsigil2/omnifall/labels/OOPS.csv"
    feature_fps: 30.0
    frames_per_feature: 16
    feature_stride: 0.033333333
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/omnifall/splits"
  - name: "wanfall"
    feature_root: "${oc.env:WANFALL_ROOT}/features/i3d"
    annotations_file: "hf://simplexsigil2/wanfall/labels/wanfall.csv"
    feature_fps: 16.0
    frames_per_feature: 1
    feature_stride: 0.0625
    feature_centered: true
    feature_type: "i3d"
    split_root: "hf://simplexsigil2/wanfall/splits/random"


num_features: 18  # Number of consecutive features to use
tokens_per_feature: 1
feature_dim: 2048  # Dimension of input features

feature_ext: ".h5"
num_classes: 10
