name: "feature-dataset-cmdfall"
feature_datasets:
  - name: "cmdfall"
    feature_root: "${oc.env:OMNIFALL_ROOT}/cmdfall/features/videomae-kinetics-7d5fps-1f"
    annotations_file: "hf://simplexsigil2/omnifall/labels/cmdfall.csv"
    feature_fps: 7.5
    frames_per_feature: 16
    feature_stride: 0.133333333
    feature_centered: false
    feature_type: "videomae-kinetics-7d5fps-1f"
    split_root: "hf://simplexsigil2/omnifall/splits"


num_features: 9  # Number of consecutive features to use
tokens_per_feature: 1
feature_dim: 768  # Dimension of input features

feature_ext: ".h5"
num_classes: 10
